version: "2.22"
services:
  server:
    container_name: "server_container"
    build: /
    ports: 
      - 8080:8080
    networks:
      - mongonet
  mongo:
    container_name: "mongo_container"
    image: mongo:latest
    environment:
     MONGO_INITDB_ROOT_USERNAME: "root"
     MONGO_INITDB_ROOT_PASSWORD: "rootpassword"
    volumes:
      - mongodb_data:/data/db
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - mongonet
  pgadmin:
    container_name: mongo_express
    image: mongo-express:latest
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: "mongouser"
      ME_CONFIG_BASICAUTH_PASSWORD: "password4mongodb"
      ME_CONFIG_MONGODB_PORT: "5432"
    volumes:
      - mongo_express:/data/express
    ports: 
      - "5050:80"
    restart: unless-stopped
    networks:
      - mongonet
networks:
  mongonet:
    driver: bridge
volumes:
  mongodb_data:
  mongo_express: