version: "2.22"
services:

  server:
    container_name: "server_container"
    build: /home/andreishyrakanau/projects/project1/GoProject1/
    ports: 
      - 8081:8081
    networks:
      - mongonet
      - postgres

  postgres:
    container_name: "postgres_container"
    image: postgres:latest
    environment:
      POSTGRES_DB: "echodb"
      POSTGRES_USER: "echopguser"
      POSTGRES_PASSWORD: "pgpw4echo"
      PGDATA: "/var/lib/postgresql/data"
    volumes:
      - echodb_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    restart: unless-stopped
    networks:
      - postgres

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: "echopguser@habr.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4echo"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports: 
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - postgres
    networks:
      - postgres

  flyway:
    image: flyway/flyway:9
    container_name: flyway
    platform: linux/amd64
    volumes:
      - "./migrations/sql:/app/sql"
    environment:
      - FLYWAY_CONNECT_RETRIES=60
      - FLYWAY_LOCATIONS=filesystem:/app/sql
      - FLYWAY_SCHEMAS=${FLYWAY_SCHEMAS}
    command: -url=jdbc:postgresql://postgres/${POSTGRES_DB} -user=${POSTGRES_USER} -password=${POSTGRES_PASSWORD} -connectRetries=60 migrate
    depends_on:
      - postgres
    networks:
      - postgres
  
  usercache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning
    volumes: 
      - cache:/userdata
    networks:
      - postgres

  rftrcache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - "6380:6380"
    command: redis-server --loglevel warning
    volumes: 
      - cache:/rfdata
    networks:
      - postgres

networks:
  postgres:
  mongonet:
volumes:
  echodb_data:
  pgadmin_data:
  mongodb_data:
  mongo_express:
  cache:
    driver: local