// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mmfshirokan/GoProject1/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PwRepositoryInterface is an autogenerated mock type for the PwRepositoryInterface type
type PwRepositoryInterface struct {
	mock.Mock
}

type PwRepositoryInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *PwRepositoryInterface) EXPECT() *PwRepositoryInterface_Expecter {
	return &PwRepositoryInterface_Expecter{mock: &_m.Mock}
}

// Compare provides a mock function with given fields: ctx, usr
func (_m *PwRepositoryInterface) Compare(ctx context.Context, usr model.User) (bool, error) {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for Compare")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, model.User) (bool, error)); ok {
		return rf(ctx, usr)
	}
	if rf, ok := ret.Get(0).(func(context.Context, model.User) bool); ok {
		r0 = rf(ctx, usr)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, model.User) error); ok {
		r1 = rf(ctx, usr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PwRepositoryInterface_Compare_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Compare'
type PwRepositoryInterface_Compare_Call struct {
	*mock.Call
}

// Compare is a helper method to define mock.On call
//   - ctx context.Context
//   - usr model.User
func (_e *PwRepositoryInterface_Expecter) Compare(ctx interface{}, usr interface{}) *PwRepositoryInterface_Compare_Call {
	return &PwRepositoryInterface_Compare_Call{Call: _e.mock.On("Compare", ctx, usr)}
}

func (_c *PwRepositoryInterface_Compare_Call) Run(run func(ctx context.Context, usr model.User)) *PwRepositoryInterface_Compare_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User))
	})
	return _c
}

func (_c *PwRepositoryInterface_Compare_Call) Return(_a0 bool, _a1 error) *PwRepositoryInterface_Compare_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PwRepositoryInterface_Compare_Call) RunAndReturn(run func(context.Context, model.User) (bool, error)) *PwRepositoryInterface_Compare_Call {
	_c.Call.Return(run)
	return _c
}

// DeletePassword provides a mock function with given fields: ctx, id
func (_m *PwRepositoryInterface) DeletePassword(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for DeletePassword")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PwRepositoryInterface_DeletePassword_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeletePassword'
type PwRepositoryInterface_DeletePassword_Call struct {
	*mock.Call
}

// DeletePassword is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *PwRepositoryInterface_Expecter) DeletePassword(ctx interface{}, id interface{}) *PwRepositoryInterface_DeletePassword_Call {
	return &PwRepositoryInterface_DeletePassword_Call{Call: _e.mock.On("DeletePassword", ctx, id)}
}

func (_c *PwRepositoryInterface_DeletePassword_Call) Run(run func(ctx context.Context, id int)) *PwRepositoryInterface_DeletePassword_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *PwRepositoryInterface_DeletePassword_Call) Return(_a0 error) *PwRepositoryInterface_DeletePassword_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PwRepositoryInterface_DeletePassword_Call) RunAndReturn(run func(context.Context, int) error) *PwRepositoryInterface_DeletePassword_Call {
	_c.Call.Return(run)
	return _c
}

// Store provides a mock function with given fields: ctx, usr
func (_m *PwRepositoryInterface) Store(ctx context.Context, usr model.User) error {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for Store")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = rf(ctx, usr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PwRepositoryInterface_Store_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Store'
type PwRepositoryInterface_Store_Call struct {
	*mock.Call
}

// Store is a helper method to define mock.On call
//   - ctx context.Context
//   - usr model.User
func (_e *PwRepositoryInterface_Expecter) Store(ctx interface{}, usr interface{}) *PwRepositoryInterface_Store_Call {
	return &PwRepositoryInterface_Store_Call{Call: _e.mock.On("Store", ctx, usr)}
}

func (_c *PwRepositoryInterface_Store_Call) Run(run func(ctx context.Context, usr model.User)) *PwRepositoryInterface_Store_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User))
	})
	return _c
}

func (_c *PwRepositoryInterface_Store_Call) Return(_a0 error) *PwRepositoryInterface_Store_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *PwRepositoryInterface_Store_Call) RunAndReturn(run func(context.Context, model.User) error) *PwRepositoryInterface_Store_Call {
	_c.Call.Return(run)
	return _c
}

// NewPwRepositoryInterface creates a new instance of PwRepositoryInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPwRepositoryInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *PwRepositoryInterface {
	mock := &PwRepositoryInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
