// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: passwordRPC.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestStore struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *PasswordData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RequestStore) Reset() {
	*x = RequestStore{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passwordRPC_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestStore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestStore) ProtoMessage() {}

func (x *RequestStore) ProtoReflect() protoreflect.Message {
	mi := &file_passwordRPC_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestStore.ProtoReflect.Descriptor instead.
func (*RequestStore) Descriptor() ([]byte, []int) {
	return file_passwordRPC_proto_rawDescGZIP(), []int{0}
}

func (x *RequestStore) GetData() *PasswordData {
	if x != nil {
		return x.Data
	}
	return nil
}

type RequestCompare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data *PasswordData `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *RequestCompare) Reset() {
	*x = RequestCompare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passwordRPC_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCompare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCompare) ProtoMessage() {}

func (x *RequestCompare) ProtoReflect() protoreflect.Message {
	mi := &file_passwordRPC_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCompare.ProtoReflect.Descriptor instead.
func (*RequestCompare) Descriptor() ([]byte, []int) {
	return file_passwordRPC_proto_rawDescGZIP(), []int{1}
}

func (x *RequestCompare) GetData() *PasswordData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ResponseCompare struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PwdValid bool `protobuf:"varint,1,opt,name=pwdValid,proto3" json:"pwdValid,omitempty"`
}

func (x *ResponseCompare) Reset() {
	*x = ResponseCompare{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passwordRPC_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseCompare) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseCompare) ProtoMessage() {}

func (x *ResponseCompare) ProtoReflect() protoreflect.Message {
	mi := &file_passwordRPC_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseCompare.ProtoReflect.Descriptor instead.
func (*ResponseCompare) Descriptor() ([]byte, []int) {
	return file_passwordRPC_proto_rawDescGZIP(), []int{2}
}

func (x *ResponseCompare) GetPwdValid() bool {
	if x != nil {
		return x.PwdValid
	}
	return false
}

type RequestDeletePassword struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *RequestDeletePassword) Reset() {
	*x = RequestDeletePassword{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passwordRPC_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeletePassword) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeletePassword) ProtoMessage() {}

func (x *RequestDeletePassword) ProtoReflect() protoreflect.Message {
	mi := &file_passwordRPC_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeletePassword.ProtoReflect.Descriptor instead.
func (*RequestDeletePassword) Descriptor() ([]byte, []int) {
	return file_passwordRPC_proto_rawDescGZIP(), []int{3}
}

func (x *RequestDeletePassword) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type PasswordData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID   int64  `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PasswordData) Reset() {
	*x = PasswordData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_passwordRPC_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PasswordData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PasswordData) ProtoMessage() {}

func (x *PasswordData) ProtoReflect() protoreflect.Message {
	mi := &file_passwordRPC_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PasswordData.ProtoReflect.Descriptor instead.
func (*PasswordData) Descriptor() ([]byte, []int) {
	return file_passwordRPC_proto_rawDescGZIP(), []int{4}
}

func (x *PasswordData) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

func (x *PasswordData) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_passwordRPC_proto protoreflect.FileDescriptor

var file_passwordRPC_proto_rawDesc = []byte{
	0x0a, 0x11, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x52, 0x50, 0x43, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x35, 0x0a, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x53, 0x74, 0x6f, 0x72, 0x65, 0x12, 0x25, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x37, 0x0a, 0x0e,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x12, 0x25,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2d, 0x0a, 0x0f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x77, 0x64, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x70, 0x77, 0x64, 0x56,
	0x61, 0x6c, 0x69, 0x64, 0x22, 0x2f, 0x0a, 0x15, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x42, 0x0a, 0x0c, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x44, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x32, 0xc0, 0x01, 0x0a, 0x08, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x34, 0x0a, 0x05, 0x53, 0x74, 0x6f, 0x72, 0x65, 0x12,
	0x11, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x53, 0x74, 0x6f,
	0x72, 0x65, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x36, 0x0a, 0x07,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x12, 0x13, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x72, 0x65, 0x1a, 0x14, 0x2e, 0x72,
	0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x72, 0x65, 0x22, 0x00, 0x12, 0x46, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61,
	0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f,
	0x72, 0x64, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04,
	0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_passwordRPC_proto_rawDescOnce sync.Once
	file_passwordRPC_proto_rawDescData = file_passwordRPC_proto_rawDesc
)

func file_passwordRPC_proto_rawDescGZIP() []byte {
	file_passwordRPC_proto_rawDescOnce.Do(func() {
		file_passwordRPC_proto_rawDescData = protoimpl.X.CompressGZIP(file_passwordRPC_proto_rawDescData)
	})
	return file_passwordRPC_proto_rawDescData
}

var file_passwordRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_passwordRPC_proto_goTypes = []interface{}{
	(*RequestStore)(nil),          // 0: rpc.requestStore
	(*RequestCompare)(nil),        // 1: rpc.requestCompare
	(*ResponseCompare)(nil),       // 2: rpc.responseCompare
	(*RequestDeletePassword)(nil), // 3: rpc.requestDeletePassword
	(*PasswordData)(nil),          // 4: rpc.passwordData
	(*emptypb.Empty)(nil),         // 5: google.protobuf.Empty
}
var file_passwordRPC_proto_depIdxs = []int32{
	4, // 0: rpc.requestStore.data:type_name -> rpc.passwordData
	4, // 1: rpc.requestCompare.data:type_name -> rpc.passwordData
	0, // 2: rpc.Password.Store:input_type -> rpc.requestStore
	1, // 3: rpc.Password.Compare:input_type -> rpc.requestCompare
	3, // 4: rpc.Password.DeletePassword:input_type -> rpc.requestDeletePassword
	5, // 5: rpc.Password.Store:output_type -> google.protobuf.Empty
	2, // 6: rpc.Password.Compare:output_type -> rpc.responseCompare
	5, // 7: rpc.Password.DeletePassword:output_type -> google.protobuf.Empty
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_passwordRPC_proto_init() }
func file_passwordRPC_proto_init() {
	if File_passwordRPC_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_passwordRPC_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestStore); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passwordRPC_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCompare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passwordRPC_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseCompare); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passwordRPC_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeletePassword); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_passwordRPC_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PasswordData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_passwordRPC_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_passwordRPC_proto_goTypes,
		DependencyIndexes: file_passwordRPC_proto_depIdxs,
		MessageInfos:      file_passwordRPC_proto_msgTypes,
	}.Build()
	File_passwordRPC_proto = out.File
	file_passwordRPC_proto_rawDesc = nil
	file_passwordRPC_proto_goTypes = nil
	file_passwordRPC_proto_depIdxs = nil
}
