// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: passwordRPC.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// PasswordClient is the client API for Password service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PasswordClient interface {
	Store(ctx context.Context, in *RequestStore, opts ...grpc.CallOption) (*emptypb.Empty, error)
	Compare(ctx context.Context, in *RequestCompare, opts ...grpc.CallOption) (*ResponseCompare, error)
	DeletePassword(ctx context.Context, in *RequestDeletePassword, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type passwordClient struct {
	cc grpc.ClientConnInterface
}

func NewPasswordClient(cc grpc.ClientConnInterface) PasswordClient {
	return &passwordClient{cc}
}

func (c *passwordClient) Store(ctx context.Context, in *RequestStore, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Password/Store", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordClient) Compare(ctx context.Context, in *RequestCompare, opts ...grpc.CallOption) (*ResponseCompare, error) {
	out := new(ResponseCompare)
	err := c.cc.Invoke(ctx, "/rpc.Password/Compare", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *passwordClient) DeletePassword(ctx context.Context, in *RequestDeletePassword, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Password/DeletePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PasswordServer is the server API for Password service.
// All implementations must embed UnimplementedPasswordServer
// for forward compatibility
type PasswordServer interface {
	Store(context.Context, *RequestStore) (*emptypb.Empty, error)
	Compare(context.Context, *RequestCompare) (*ResponseCompare, error)
	DeletePassword(context.Context, *RequestDeletePassword) (*emptypb.Empty, error)
	mustEmbedUnimplementedPasswordServer()
}

// UnimplementedPasswordServer must be embedded to have forward compatible implementations.
type UnimplementedPasswordServer struct {
}

func (UnimplementedPasswordServer) Store(context.Context, *RequestStore) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedPasswordServer) Compare(context.Context, *RequestCompare) (*ResponseCompare, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Compare not implemented")
}
func (UnimplementedPasswordServer) DeletePassword(context.Context, *RequestDeletePassword) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePassword not implemented")
}
func (UnimplementedPasswordServer) mustEmbedUnimplementedPasswordServer() {}

// UnsafePasswordServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PasswordServer will
// result in compilation errors.
type UnsafePasswordServer interface {
	mustEmbedUnimplementedPasswordServer()
}

func RegisterPasswordServer(s grpc.ServiceRegistrar, srv PasswordServer) {
	s.RegisterService(&Password_ServiceDesc, srv)
}

func _Password_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestStore)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Password/Store",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordServer).Store(ctx, req.(*RequestStore))
	}
	return interceptor(ctx, in, info, handler)
}

func _Password_Compare_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCompare)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordServer).Compare(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Password/Compare",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordServer).Compare(ctx, req.(*RequestCompare))
	}
	return interceptor(ctx, in, info, handler)
}

func _Password_DeletePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeletePassword)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PasswordServer).DeletePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Password/DeletePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PasswordServer).DeletePassword(ctx, req.(*RequestDeletePassword))
	}
	return interceptor(ctx, in, info, handler)
}

// Password_ServiceDesc is the grpc.ServiceDesc for Password service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Password_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Password",
	HandlerType: (*PasswordServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Store",
			Handler:    _Password_Store_Handler,
		},
		{
			MethodName: "Compare",
			Handler:    _Password_Compare_Handler,
		},
		{
			MethodName: "DeletePassword",
			Handler:    _Password_DeletePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "passwordRPC.proto",
}
