// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: tokenRPC.proto

package rpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TokenClient is the client API for Token service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TokenClient interface {
	CreateRfToken(ctx context.Context, in *RequestCreateRfToken, opts ...grpc.CallOption) (*emptypb.Empty, error)
	DeleteRftToken(ctx context.Context, in *RequestDeleteRftToken, opts ...grpc.CallOption) (*emptypb.Empty, error)
	GetByUserID(ctx context.Context, in *RequestGetByUserID, opts ...grpc.CallOption) (*ResponseGetByUserID, error)
}

type tokenClient struct {
	cc grpc.ClientConnInterface
}

func NewTokenClient(cc grpc.ClientConnInterface) TokenClient {
	return &tokenClient{cc}
}

func (c *tokenClient) CreateRfToken(ctx context.Context, in *RequestCreateRfToken, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Token/CreateRfToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) DeleteRftToken(ctx context.Context, in *RequestDeleteRftToken, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/rpc.Token/DeleteRftToken", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tokenClient) GetByUserID(ctx context.Context, in *RequestGetByUserID, opts ...grpc.CallOption) (*ResponseGetByUserID, error) {
	out := new(ResponseGetByUserID)
	err := c.cc.Invoke(ctx, "/rpc.Token/GetByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TokenServer is the server API for Token service.
// All implementations must embed UnimplementedTokenServer
// for forward compatibility
type TokenServer interface {
	CreateRfToken(context.Context, *RequestCreateRfToken) (*emptypb.Empty, error)
	DeleteRftToken(context.Context, *RequestDeleteRftToken) (*emptypb.Empty, error)
	GetByUserID(context.Context, *RequestGetByUserID) (*ResponseGetByUserID, error)
	mustEmbedUnimplementedTokenServer()
}

// UnimplementedTokenServer must be embedded to have forward compatible implementations.
type UnimplementedTokenServer struct {
}

func (UnimplementedTokenServer) CreateRfToken(context.Context, *RequestCreateRfToken) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRfToken not implemented")
}
func (UnimplementedTokenServer) DeleteRftToken(context.Context, *RequestDeleteRftToken) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRftToken not implemented")
}
func (UnimplementedTokenServer) GetByUserID(context.Context, *RequestGetByUserID) (*ResponseGetByUserID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetByUserID not implemented")
}
func (UnimplementedTokenServer) mustEmbedUnimplementedTokenServer() {}

// UnsafeTokenServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TokenServer will
// result in compilation errors.
type UnsafeTokenServer interface {
	mustEmbedUnimplementedTokenServer()
}

func RegisterTokenServer(s grpc.ServiceRegistrar, srv TokenServer) {
	s.RegisterService(&Token_ServiceDesc, srv)
}

func _Token_CreateRfToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestCreateRfToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).CreateRfToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Token/CreateRfToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).CreateRfToken(ctx, req.(*RequestCreateRfToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_DeleteRftToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestDeleteRftToken)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).DeleteRftToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Token/DeleteRftToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).DeleteRftToken(ctx, req.(*RequestDeleteRftToken))
	}
	return interceptor(ctx, in, info, handler)
}

func _Token_GetByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetByUserID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TokenServer).GetByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/rpc.Token/GetByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TokenServer).GetByUserID(ctx, req.(*RequestGetByUserID))
	}
	return interceptor(ctx, in, info, handler)
}

// Token_ServiceDesc is the grpc.ServiceDesc for Token service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Token_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.Token",
	HandlerType: (*TokenServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateRfToken",
			Handler:    _Token_CreateRfToken_Handler,
		},
		{
			MethodName: "DeleteRftToken",
			Handler:    _Token_DeleteRftToken_Handler,
		},
		{
			MethodName: "GetByUserID",
			Handler:    _Token_GetByUserID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "tokenRPC.proto",
}
