// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v4.25.1
// source: tokenRPC.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RequestCreateRfToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *RequestCreateRfToken) Reset() {
	*x = RequestCreateRfToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenRPC_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestCreateRfToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestCreateRfToken) ProtoMessage() {}

func (x *RequestCreateRfToken) ProtoReflect() protoreflect.Message {
	mi := &file_tokenRPC_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestCreateRfToken.ProtoReflect.Descriptor instead.
func (*RequestCreateRfToken) Descriptor() ([]byte, []int) {
	return file_tokenRPC_proto_rawDescGZIP(), []int{0}
}

func (x *RequestCreateRfToken) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type RequestDeleteRftToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *RequestDeleteRftToken) Reset() {
	*x = RequestDeleteRftToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenRPC_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDeleteRftToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDeleteRftToken) ProtoMessage() {}

func (x *RequestDeleteRftToken) ProtoReflect() protoreflect.Message {
	mi := &file_tokenRPC_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDeleteRftToken.ProtoReflect.Descriptor instead.
func (*RequestDeleteRftToken) Descriptor() ([]byte, []int) {
	return file_tokenRPC_proto_rawDescGZIP(), []int{1}
}

func (x *RequestDeleteRftToken) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type RequestGetByUserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserID int64 `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
}

func (x *RequestGetByUserID) Reset() {
	*x = RequestGetByUserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenRPC_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestGetByUserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestGetByUserID) ProtoMessage() {}

func (x *RequestGetByUserID) ProtoReflect() protoreflect.Message {
	mi := &file_tokenRPC_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestGetByUserID.ProtoReflect.Descriptor instead.
func (*RequestGetByUserID) Descriptor() ([]byte, []int) {
	return file_tokenRPC_proto_rawDescGZIP(), []int{2}
}

func (x *RequestGetByUserID) GetUserID() int64 {
	if x != nil {
		return x.UserID
	}
	return 0
}

type ResponseGetByUserID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Rft []*ResponseGetByUserIDRefreshToken `protobuf:"bytes,1,rep,name=rft,proto3" json:"rft,omitempty"`
}

func (x *ResponseGetByUserID) Reset() {
	*x = ResponseGetByUserID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenRPC_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetByUserID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetByUserID) ProtoMessage() {}

func (x *ResponseGetByUserID) ProtoReflect() protoreflect.Message {
	mi := &file_tokenRPC_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetByUserID.ProtoReflect.Descriptor instead.
func (*ResponseGetByUserID) Descriptor() ([]byte, []int) {
	return file_tokenRPC_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseGetByUserID) GetRft() []*ResponseGetByUserIDRefreshToken {
	if x != nil {
		return x.Rft
	}
	return nil
}

type UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Male bool   `protobuf:"varint,3,opt,name=male,proto3" json:"male,omitempty"`
}

func (x *UserData) Reset() {
	*x = UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenRPC_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_tokenRPC_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_tokenRPC_proto_rawDescGZIP(), []int{4}
}

func (x *UserData) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserData) GetMale() bool {
	if x != nil {
		return x.Male
	}
	return false
}

type ResponseGetByUserIDRefreshToken struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Uuid       string                 `protobuf:"bytes,2,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Hash       string                 `protobuf:"bytes,3,opt,name=hash,proto3" json:"hash,omitempty"`
	Expiration *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=expiration,proto3" json:"expiration,omitempty"`
}

func (x *ResponseGetByUserIDRefreshToken) Reset() {
	*x = ResponseGetByUserIDRefreshToken{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tokenRPC_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseGetByUserIDRefreshToken) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseGetByUserIDRefreshToken) ProtoMessage() {}

func (x *ResponseGetByUserIDRefreshToken) ProtoReflect() protoreflect.Message {
	mi := &file_tokenRPC_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseGetByUserIDRefreshToken.ProtoReflect.Descriptor instead.
func (*ResponseGetByUserIDRefreshToken) Descriptor() ([]byte, []int) {
	return file_tokenRPC_proto_rawDescGZIP(), []int{3, 0}
}

func (x *ResponseGetByUserIDRefreshToken) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ResponseGetByUserIDRefreshToken) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *ResponseGetByUserIDRefreshToken) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

func (x *ResponseGetByUserIDRefreshToken) GetExpiration() *timestamppb.Timestamp {
	if x != nil {
		return x.Expiration
	}
	return nil
}

var File_tokenRPC_proto protoreflect.FileDescriptor

var file_tokenRPC_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x50, 0x43, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x72, 0x70, 0x63, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x2e, 0x0a, 0x14, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x44, 0x22, 0x2b, 0x0a, 0x15, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x66, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x75, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x22, 0x2c, 0x0a, 0x12, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0xdb,
	0x01, 0x0a, 0x13, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47, 0x65, 0x74, 0x42, 0x79,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x37, 0x0a, 0x03, 0x72, 0x66, 0x74, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x2e, 0x72, 0x65,
	0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x03, 0x72, 0x66, 0x74, 0x1a,
	0x8a, 0x01, 0x0a, 0x0c, 0x72, 0x65, 0x66, 0x72, 0x65, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x12, 0x3a, 0x0a, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x0a, 0x65, 0x78, 0x70, 0x69, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x42, 0x0a, 0x08,
	0x75, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04,
	0x6d, 0x61, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x6d, 0x61, 0x6c, 0x65,
	0x32, 0xd9, 0x01, 0x0a, 0x05, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x44, 0x0a, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x19, 0x2e, 0x72, 0x70,
	0x63, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x66, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00,
	0x12, 0x46, 0x0a, 0x0e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x66, 0x74, 0x54, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x66, 0x74, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x1a, 0x16,
	0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66,
	0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0b, 0x47, 0x65, 0x74, 0x42,
	0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x12, 0x17, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x47, 0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44,
	0x1a, 0x18, 0x2e, 0x72, 0x70, 0x63, 0x2e, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x47,
	0x65, 0x74, 0x42, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x44, 0x22, 0x00, 0x42, 0x06, 0x5a, 0x04,
	0x2f, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tokenRPC_proto_rawDescOnce sync.Once
	file_tokenRPC_proto_rawDescData = file_tokenRPC_proto_rawDesc
)

func file_tokenRPC_proto_rawDescGZIP() []byte {
	file_tokenRPC_proto_rawDescOnce.Do(func() {
		file_tokenRPC_proto_rawDescData = protoimpl.X.CompressGZIP(file_tokenRPC_proto_rawDescData)
	})
	return file_tokenRPC_proto_rawDescData
}

var file_tokenRPC_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_tokenRPC_proto_goTypes = []interface{}{
	(*RequestCreateRfToken)(nil),            // 0: rpc.requestCreateRfToken
	(*RequestDeleteRftToken)(nil),           // 1: rpc.requestDeleteRftToken
	(*RequestGetByUserID)(nil),              // 2: rpc.requestGetByUserID
	(*ResponseGetByUserID)(nil),             // 3: rpc.responseGetByUserID
	(*UserData)(nil),                        // 4: rpc.userData
	(*ResponseGetByUserIDRefreshToken)(nil), // 5: rpc.responseGetByUserID.refreshToken
	(*timestamppb.Timestamp)(nil),           // 6: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                   // 7: google.protobuf.Empty
}
var file_tokenRPC_proto_depIdxs = []int32{
	5, // 0: rpc.responseGetByUserID.rft:type_name -> rpc.responseGetByUserID.refreshToken
	6, // 1: rpc.responseGetByUserID.refreshToken.expiration:type_name -> google.protobuf.Timestamp
	0, // 2: rpc.Token.CreateRfToken:input_type -> rpc.requestCreateRfToken
	1, // 3: rpc.Token.DeleteRftToken:input_type -> rpc.requestDeleteRftToken
	2, // 4: rpc.Token.GetByUserID:input_type -> rpc.requestGetByUserID
	7, // 5: rpc.Token.CreateRfToken:output_type -> google.protobuf.Empty
	7, // 6: rpc.Token.DeleteRftToken:output_type -> google.protobuf.Empty
	3, // 7: rpc.Token.GetByUserID:output_type -> rpc.responseGetByUserID
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_tokenRPC_proto_init() }
func file_tokenRPC_proto_init() {
	if File_tokenRPC_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tokenRPC_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestCreateRfToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenRPC_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDeleteRftToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenRPC_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestGetByUserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenRPC_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetByUserID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenRPC_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tokenRPC_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseGetByUserIDRefreshToken); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tokenRPC_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tokenRPC_proto_goTypes,
		DependencyIndexes: file_tokenRPC_proto_depIdxs,
		MessageInfos:      file_tokenRPC_proto_msgTypes,
	}.Build()
	File_tokenRPC_proto = out.File
	file_tokenRPC_proto_rawDesc = nil
	file_tokenRPC_proto_goTypes = nil
	file_tokenRPC_proto_depIdxs = nil
}
