// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: imageRPC.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ImageClient is the client API for Image service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ImageClient interface {
	DownloadImage(ctx context.Context, in *RequestDownloadImage, opts ...grpc.CallOption) (Image_DownloadImageClient, error)
	UploadImage(ctx context.Context, opts ...grpc.CallOption) (Image_UploadImageClient, error)
}

type imageClient struct {
	cc grpc.ClientConnInterface
}

func NewImageClient(cc grpc.ClientConnInterface) ImageClient {
	return &imageClient{cc}
}

func (c *imageClient) DownloadImage(ctx context.Context, in *RequestDownloadImage, opts ...grpc.CallOption) (Image_DownloadImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Image_ServiceDesc.Streams[0], "/pb.Image/DownloadImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageDownloadImageClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Image_DownloadImageClient interface {
	Recv() (*ResponseDownloadImage, error)
	grpc.ClientStream
}

type imageDownloadImageClient struct {
	grpc.ClientStream
}

func (x *imageDownloadImageClient) Recv() (*ResponseDownloadImage, error) {
	m := new(ResponseDownloadImage)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *imageClient) UploadImage(ctx context.Context, opts ...grpc.CallOption) (Image_UploadImageClient, error) {
	stream, err := c.cc.NewStream(ctx, &Image_ServiceDesc.Streams[1], "/pb.Image/UploadImage", opts...)
	if err != nil {
		return nil, err
	}
	x := &imageUploadImageClient{stream}
	return x, nil
}

type Image_UploadImageClient interface {
	Send(*RequestUploadImage) error
	CloseAndRecv() (*emptypb.Empty, error)
	grpc.ClientStream
}

type imageUploadImageClient struct {
	grpc.ClientStream
}

func (x *imageUploadImageClient) Send(m *RequestUploadImage) error {
	return x.ClientStream.SendMsg(m)
}

func (x *imageUploadImageClient) CloseAndRecv() (*emptypb.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(emptypb.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ImageServer is the server API for Image service.
// All implementations must embed UnimplementedImageServer
// for forward compatibility
type ImageServer interface {
	DownloadImage(*RequestDownloadImage, Image_DownloadImageServer) error
	UploadImage(Image_UploadImageServer) error
	mustEmbedUnimplementedImageServer()
}

// UnimplementedImageServer must be embedded to have forward compatible implementations.
type UnimplementedImageServer struct {
}

func (UnimplementedImageServer) DownloadImage(*RequestDownloadImage, Image_DownloadImageServer) error {
	return status.Errorf(codes.Unimplemented, "method DownloadImage not implemented")
}
func (UnimplementedImageServer) UploadImage(Image_UploadImageServer) error {
	return status.Errorf(codes.Unimplemented, "method UploadImage not implemented")
}
func (UnimplementedImageServer) mustEmbedUnimplementedImageServer() {}

// UnsafeImageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ImageServer will
// result in compilation errors.
type UnsafeImageServer interface {
	mustEmbedUnimplementedImageServer()
}

func RegisterImageServer(s grpc.ServiceRegistrar, srv ImageServer) {
	s.RegisterService(&Image_ServiceDesc, srv)
}

func _Image_DownloadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(RequestDownloadImage)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ImageServer).DownloadImage(m, &imageDownloadImageServer{stream})
}

type Image_DownloadImageServer interface {
	Send(*ResponseDownloadImage) error
	grpc.ServerStream
}

type imageDownloadImageServer struct {
	grpc.ServerStream
}

func (x *imageDownloadImageServer) Send(m *ResponseDownloadImage) error {
	return x.ServerStream.SendMsg(m)
}

func _Image_UploadImage_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ImageServer).UploadImage(&imageUploadImageServer{stream})
}

type Image_UploadImageServer interface {
	SendAndClose(*emptypb.Empty) error
	Recv() (*RequestUploadImage, error)
	grpc.ServerStream
}

type imageUploadImageServer struct {
	grpc.ServerStream
}

func (x *imageUploadImageServer) SendAndClose(m *emptypb.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *imageUploadImageServer) Recv() (*RequestUploadImage, error) {
	m := new(RequestUploadImage)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Image_ServiceDesc is the grpc.ServiceDesc for Image service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Image_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Image",
	HandlerType: (*ImageServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DownloadImage",
			Handler:       _Image_DownloadImage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadImage",
			Handler:       _Image_UploadImage_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "imageRPC.proto",
}
