// Code generated by mockery v2.39.1. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/mmfshirokan/GoProject1/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// UserInterface is an autogenerated mock type for the UserInterface type
type UserInterface struct {
	mock.Mock
}

type UserInterface_Expecter struct {
	mock *mock.Mock
}

func (_m *UserInterface) EXPECT() *UserInterface_Expecter {
	return &UserInterface_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, usr
func (_m *UserInterface) Create(ctx context.Context, usr model.User) error {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = rf(ctx, usr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserInterface_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UserInterface_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - usr model.User
func (_e *UserInterface_Expecter) Create(ctx interface{}, usr interface{}) *UserInterface_Create_Call {
	return &UserInterface_Create_Call{Call: _e.mock.On("Create", ctx, usr)}
}

func (_c *UserInterface_Create_Call) Run(run func(ctx context.Context, usr model.User)) *UserInterface_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User))
	})
	return _c
}

func (_c *UserInterface_Create_Call) Return(_a0 error) *UserInterface_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserInterface_Create_Call) RunAndReturn(run func(context.Context, model.User) error) *UserInterface_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function with given fields: ctx, id
func (_m *UserInterface) Delete(ctx context.Context, id int) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserInterface_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type UserInterface_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *UserInterface_Expecter) Delete(ctx interface{}, id interface{}) *UserInterface_Delete_Call {
	return &UserInterface_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *UserInterface_Delete_Call) Run(run func(ctx context.Context, id int)) *UserInterface_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *UserInterface_Delete_Call) Return(_a0 error) *UserInterface_Delete_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserInterface_Delete_Call) RunAndReturn(run func(context.Context, int) error) *UserInterface_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetTroughID provides a mock function with given fields: ctx, id
func (_m *UserInterface) GetTroughID(ctx context.Context, id int) (*model.User, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetTroughID")
	}

	var r0 *model.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int) (*model.User, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int) *model.User); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserInterface_GetTroughID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTroughID'
type UserInterface_GetTroughID_Call struct {
	*mock.Call
}

// GetTroughID is a helper method to define mock.On call
//   - ctx context.Context
//   - id int
func (_e *UserInterface_Expecter) GetTroughID(ctx interface{}, id interface{}) *UserInterface_GetTroughID_Call {
	return &UserInterface_GetTroughID_Call{Call: _e.mock.On("GetTroughID", ctx, id)}
}

func (_c *UserInterface_GetTroughID_Call) Run(run func(ctx context.Context, id int)) *UserInterface_GetTroughID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int))
	})
	return _c
}

func (_c *UserInterface_GetTroughID_Call) Return(usr *model.User, err error) *UserInterface_GetTroughID_Call {
	_c.Call.Return(usr, err)
	return _c
}

func (_c *UserInterface_GetTroughID_Call) RunAndReturn(run func(context.Context, int) (*model.User, error)) *UserInterface_GetTroughID_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function with given fields: ctx, usr
func (_m *UserInterface) Update(ctx context.Context, usr model.User) error {
	ret := _m.Called(ctx, usr)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, model.User) error); ok {
		r0 = rf(ctx, usr)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UserInterface_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UserInterface_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - usr model.User
func (_e *UserInterface_Expecter) Update(ctx interface{}, usr interface{}) *UserInterface_Update_Call {
	return &UserInterface_Update_Call{Call: _e.mock.On("Update", ctx, usr)}
}

func (_c *UserInterface_Update_Call) Run(run func(ctx context.Context, usr model.User)) *UserInterface_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(model.User))
	})
	return _c
}

func (_c *UserInterface_Update_Call) Return(_a0 error) *UserInterface_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UserInterface_Update_Call) RunAndReturn(run func(context.Context, model.User) error) *UserInterface_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUserInterface creates a new instance of UserInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserInterface {
	mock := &UserInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
